# Generated by Django 4.0.3 on 2022-06-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i18n', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
