# Generated by Django 4.0.3 on 2022-04-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0003_alter_language_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('english', models.TextField()),
                ('ipa', models.TextField()),
                ('date', models.DateField(null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
            ],
            options={
                'db_table': 'solution',
                'ordering': ['-order'],
            },
        ),
    ]
