# Generated by Django 4.0.3 on 2022-05-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0006_alter_language_genus_alter_language_lang_id_and_more'),
        ('solution', '0002_alter_solution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='alternates',
            field=models.ManyToManyField(blank=True, related_name='alternate_solution', to='language.language'),
        ),
    ]
