# Generated by Django 4.0.3 on 2022-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_solution_alternates'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='romanization',
            field=models.TextField(blank=True),
        ),
    ]
