# Generated by Django 4.0.3 on 2022-05-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0005_solution_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='victory_message',
            field=models.TextField(blank=True),
        ),
    ]
