# Generated by Django 4.0.3 on 2022-06-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0007_solution_hidden_options_alter_solution_alternates'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='freeze_date',
            field=models.BooleanField(default=False),
        ),
    ]
