# Generated by Django 4.0.3 on 2022-06-19 20:12

from django.db import migrations, models


def populate_translations(apps, schema_editor):
    Translation = apps.get_model('i18n', 'Translation')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Solution = apps.get_model('solution', 'Solution')

    ct, _ = ContentType.objects.get_or_create(app_label='solution', model='solution')
    translations = Translation.objects.filter(content_type=ct)
    for obj in Solution.objects.all():
        for translation in translations.filter(object_id=obj.id):
            setattr(obj, translation.language, translation.value)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0008_solution_freeze_date'),
        ('i18n', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='es',
            field=models.TextField(default='', verbose_name='spanish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='fr',
            field=models.TextField(default='', verbose_name='french'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_translations, reverse_code=lambda a,b: None)
    ]
