# Generated by Django 4.0.3 on 2022-06-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0009_solution_es_solution_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='zh',
            field=models.TextField(default='', verbose_name='chinese'),
            preserve_default=False,
        ),
    ]
