# Generated by Django 4.0.3 on 2022-06-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0010_solution_zh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='es',
            field=models.TextField(blank=True, verbose_name='spanish'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='fr',
            field=models.TextField(blank=True, verbose_name='french'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='zh',
            field=models.TextField(blank=True, verbose_name='chinese'),
        ),
    ]
