# Generated by Django 4.0.3 on 2022-07-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0011_alter_solution_es_alter_solution_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='vertical',
            field=models.BooleanField(default=False),
        ),
    ]
