# Generated by Django 4.2.23 on 2025-07-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0012_solution_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='copy_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_from', to='solution.solution'),
        ),
    ]
