# Generated by Django 4.0.3 on 2022-04-11 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.family')),
            ],
        ),
        migrations.CreateModel(
            name='Macroarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subfamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.family')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('lang_id', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=11, max_digits=14)),
                ('longitude', models.DecimalField(decimal_places=11, max_digits=14)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.family')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.genus')),
                ('macroarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.macroarea')),
                ('subfamily', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.subfamily')),
            ],
        ),
        migrations.AddField(
            model_name='genus',
            name='subfamily',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.subfamily'),
        ),
    ]
