# Generated by Django 4.0.3 on 2022-04-11 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.genus'),
        ),
    ]
