# Generated by Django 4.0.3 on 2022-04-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_alter_language_genus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
    ]
