# Generated by Django 4.0.3 on 2022-05-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_alter_language_latitude_alter_language_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='language',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
