# Generated by Django 4.0.3 on 2022-05-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0005_alter_language_options_language_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='genus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.genus'),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='subfamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.subfamily'),
        ),
    ]
