# Generated by Django 4.0.3 on 2022-05-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0006_alter_language_genus_alter_language_lang_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name_plural': 'Genera'},
        ),
        migrations.AlterModelOptions(
            name='subfamily',
            options={'verbose_name_plural': 'Subamilies'},
        ),
    ]
