# Generated by Django 4.0.3 on 2022-06-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0007_alter_family_options_alter_genus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='other_names',
            field=models.JSONField(blank=True, default=[]),
            preserve_default=False,
        ),
    ]
