# Generated by Django 4.0.3 on 2022-06-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0010_family_es_family_fr_genus_es_genus_fr_language_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='zh',
            field=models.TextField(default='', verbose_name='chinese'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genus',
            name='zh',
            field=models.TextField(default='', verbose_name='chinese'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='zh',
            field=models.TextField(default='', verbose_name='chinese'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='macroarea',
            name='zh',
            field=models.TextField(default='', verbose_name='chinese'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfamily',
            name='zh',
            field=models.TextField(default='', verbose_name='chinese'),
            preserve_default=False,
        ),
    ]
