# Generated by Django 4.0.3 on 2022-06-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0011_family_zh_genus_zh_language_zh_macroarea_zh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='subfamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.subfamily'),
        ),
    ]
